python BERT_SL.py \
--task_name="MSDS" \
--do_lower_case=True \
--crf=False \
--do_train=False \
--do_eval=False \
--do_predict=True \
--data_dir=data \
--vocab_file=checkpoint/chinese_L-12_H-768_A-12/vocab.txt \
--bert_config_file=checkpoint/chinese_L-12_H-768_A-12/bert_config.json \
--init_checkpoint=checkpoint/chinese_L-12_H-768_A-12/bert_model.ckpt \
--max_seq_length=128 \
--train_batch_size=32 \
--learning_rate=2e-5 \
--num_train_epochs=10.0 \
--output_dir=./output